[package]
name = "loom-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
directories = { workspace = true }
dirs = { workspace = true }
which = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = { workspace = true }
winapi = { version = "0.3.9", features = [
  "winuser",
  "minwindef",
  "winnt",
] }

[dev-dependencies]
tempfile = { workspace = true }
